# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenJTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openJTalk', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Roid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('voiceModel', models.FileField(upload_to='voices/%Y/%m/%d/')),
                ('figure', models.ImageField(upload_to='figure/%Y/%m/%d/')),
            ],
        ),
    ]
