# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_auto_20160910_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjtalk',
            name='openJTalk',
            field=models.FilePathField(path=b'/home/qh73xe/Documents/prod/forODA/SRP/_TOOLS/bin'),
        ),
    ]
